name: test artifacts jobs
on: [push]
jobs:
  build:
    name: Building packages
    runs-on: ubuntu-18.04
    steps:
      - name: create artifacts
        shell: bash
        run: |
          mkdir -p ./zfs-localrepo
          echo 'test123' >> ./zfs-localrepo/test123.txt
          echo 'test456' >> ./zfs-localrepo/test456.txt
      - name: Cache files
        uses: actions/cache@v1
        with:
          path: ./zfs-localrepo
          key: ${{ runner.OS }}-zfs-${{ github.sha }}
  test:
    needs: build
    name: Testing packages
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        testbatch:
           - 'test123'
           - 'test456'
    steps:
      - name: Restore cached files
        uses: actions/cache@v1
        with:
          path: ./zfs-localrepo
          key: ${{ runner.OS }}-zfs-${{ github.sha }}
      - name: list artifacts
        shell: bash
        run: |
          ls ./zfs-localrepo -alt
          cat ./zfs-localrepo/${{ matrix.testbatch }}.txt
         
