name: test artifacts jobs
on: [push]
jobs:
  deploy:
    name: Deploying artefacts
    runs-on: ubuntu-18.04
    steps:
      - name: add module
        shell: bash
        run: |
          sudo linux-image-extra-virtual-hwe-18.04 linux-image-extra-virtual-hwe-18.04-edge
          sudo find /lib -name scsi_debug*.*
