name: test artifacts jobs
on: [push]
jobs:
  deploy:
    name: Deploying artefacts
    runs-on: ubuntu-18.04
    steps:
      - name: add module
        shell: bash
        run: |
          sudo apt update
          sudo apt-cache search $(uname -r)
          sudo apt install -yq linux-modules-extra-$(uname -r)
          sudo find /lib -name scsi_debug*.*
          sudo modprobe scsi_debug
