name: test artifacts jobs
on: [push]
jobs:
  deploy:
    name: Deploying artefacts
    runs-on: ubuntu-18.04
    steps:
      - name: add module
        shell: bash
        run: |
          sudo apt list --installed | grep linux-image
          sudo apt install -yq linux-image-extra-$(uname -r)
          sudo find /lib -name scsi_debug*.*
