name: test artifacts jobs
on: [push]
jobs:
  deploy:
    name: Deploying artefacts
    runs-on: ubuntu-18.04
    steps:
      - name: add module
        shell: bash
        run: |
          sudo find / -name scsi_debug*.*
