name: test artifacts jobs
on: [push]
jobs:
  deploy:
    name: Deploying artefacts
    runs-on: ubuntu-18.04
    steps:
      - name: add module
        shell: bash
        run: |
          sudo ls -al /lib/modules/$(uname -r)/kernel/drivers/scsi/
