name: test artifacts jobs
on: [push]
jobs:
  deploy:
    name: Deploying artefacts
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: adding required packages for repo publishing
        shell: bash
        run: |
          sudo bash -c "echo 'deb http://repo.aptly.info/ squeeze main' >> /etc/apt/sources.list"
          sudo DEBIAN_FRONTEND=noninteractive apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install gnupg aptly
      - name: create repo and add packages
        shell: bash
        run: |
          aptly repo create -distribution="bionic" zfs-backports-experimental
          sed -i 's/\"architectures\": \[\]/\"architectures\": \[\"amd64\"\]/g' ~/.aptly.conf
          echo ${{ secrets.GPG_PASS }} | gpg --batch --import ./apt-private-key.asc
          ls ./*.deb -1 | xargs aptly repo add zfs-backports-experimental         
          aptly publish repo --gpg-key="74191A3222C2FFD5" --batch=true --passphrase="${{ secrets.GPG_PASS }}" zfs-backports-experimental 
          aptly repo show -with-packages zfs-backports-experimental
          find /home/runner/.aptly/public -name '*.deb'
  build:
    name: Building packages
    runs-on: ubuntu-18.04
    steps:
      - name: create artifacts
        shell: bash
        run: |
          sudo mkdir -p /work/zfs-localrepo
          sudo bash -c "echo 'test123' >> /work/zfs-localrepo/test123.txt"
          sudo bash -c "echo 'test456' >> /work/zfs-localrepo/test456.txt"
      - uses: actions/upload-artifact@v1
        with:
          name: test-pkg1
          path: /work/zfs-localrepo
  test:
    needs: build
    name: Testing packages
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        testbatch:
           - 'test123'
           - 'test456'
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: test-pkg1
      - name: list artifacts
        shell: bash
        run: |
          ls ./test-pkg1 -alt
          cat ./test-pkg1/${{ matrix.testbatch }}.txt
         
